name:               "Nchos Tech"
description:        "Deep Learning Engineer "

url:                ""
author:             "So Jae Woo"
email:              "nchos88@gmail.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "nchos88@gmail"
github:             "https://github.com/nchos88"
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   "thinker3197"

background:         "https://images.pexels.com/photos/325185/pexels-photo-325185.jpeg?cs=srgb&dl=architecture-buildings-business-325185.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"
  - name:           "Paper Review"
    href:           "/paper"
  - name:           "Deep Learning with Python"
    href:           "/dlpython"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate